// Generated by CoffeeScript 1.7.1

/* @author Abed Halawi <abed.halawi@vinelab.com> */

(function() {
  var Session, base64id, q,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  q = require('q');

  base64id = require('base64id');

  Session = (function() {

    /*
     * Create a new instance of this class.
     *
     * @param {string} namespace
     * @param {object} RedisClient The redis client.
     */
    function Session(config, RedisClient) {
      this.config = config;
      this.RedisClient = RedisClient;
      this.storeKey = __bind(this.storeKey, this);
      this.destroy = __bind(this.destroy, this);
      this.remove = __bind(this.remove, this);
      this.get = __bind(this.get, this);
      this.put = __bind(this.put, this);
      this.has = __bind(this.has, this);
      this.id = base64id.generateId();
      this.is_active = true;
    }


    /*
     * Determine whether a key exists for this session.
     *
     * @param {string} key
     */

    Session.prototype.has = function(key) {
      var dfd;
      dfd = q.defer();
      this.RedisClient.exists(this.storeKey(key), function(err, exists) {
        if (err != null) {
          return dfd.reject(err);
        }
        return dfd.resolve(Boolean(exists));
      });
      return dfd.promise;
    };


    /*
     * Put a key/value pair or an array of key/value pairs
     *  in the session.
     *
     *  @param {string|object} key
     *  @param {mixed} value* (Optional)
     */

    Session.prototype.put = function(key, value) {
      var dfd, field, pairs, values;
      dfd = q.defer();
      pairs = [];
      if (typeof key !== 'object') {
        pairs = [this.storeKey(key), value];
      } else {
        for (field in key) {
          value = key[field];
          pairs.push(this.storeKey(field), value);
        }
      }
      values = pairs;
      values.push(function(err, result) {
        if (err != null) {
          return dfd.reject(err);
        }
        return dfd.resolve(result);
      });
      this.RedisClient.mset.apply(this.RedisClient, values);
      return dfd.promise;
    };


    /*
     * Get an item from the session.
     *
     * @param {string|array} key
     * @param {mixed} default
     */

    Session.prototype.get = function(key) {
      var dfd, keys, values;
      dfd = q.defer();
      keys = typeof key !== 'array' ? [key] : key;
      values = keys.map(this.storeKey);
      values.push(function(err, result) {
        var e;
        if (err != null) {
          return dfd.reject(err);
        }
        if (typeof key === 'string') {
          result = result.pop();
        }
        try {
          result = JSON.parse(result)._v;
        } catch (_error) {
          e = _error;
          result = result;
        }
        return dfd.resolve(result);
      });
      this.RedisClient.mget.apply(this.RedisClient, values);
      return dfd.promise;
    };


    /*
     * Remove a key from the session.
     *
     * @param {string|array} key
     */

    Session.prototype.remove = function(key) {
      var dfd;
      dfd = q.defer();
      this.RedisClient.del(this.storeKey(key), (function(_this) {
        return function(err, removed) {
          if (err != null) {
            return dfd.reject(err);
          }
          return dfd.resolve(Boolean(removed));
        };
      })(this));
      return dfd.promise;
    };


    /*
     * Destroy this session.
     */

    Session.prototype.destroy = function() {
      var dfd;
      dfd = q.defer();
      this.RedisClient.keys("*:" + this.id + ":*", (function(_this) {
        return function(err, keys) {
          if (err != null) {
            return dfd.reject(err);
          }
          return _this.RedisClient.del(keys, function(err, destroyed) {
            if (err != null) {
              return dfd.reject(err);
            }
            _this.is_active = false;
            return dfd.resolve(Boolean(destroyed));
          });
        };
      })(this));
      return dfd.promise;
    };


    /*
     * Generate the hash key for this session.
     *
     * @param {string} key
     */

    Session.prototype.storeKey = function(key) {
      return "" + this.config.session.prefix + ":" + this.id + ":" + key;
    };

    return Session;

  })();

  module.exports.klass = Session;

}).call(this);
